# Generated by Django 3.1 on 2021-04-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210420_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='createdAt',
        ),
    ]
