# Generated by Django 3.1 on 2021-04-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210420_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amounts',
            new_name='amount',
        ),
    ]
